# Generated by Django 3.2.5 on 2021-07-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('location_ind', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDIAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveBigIntegerField()),
                ('type_action', models.CharField(choices=[('CREATION', 'CREATION'), ('MODIFICATION', 'MODIFICATION'), ('CONTROLE', 'CONTROLE')], max_length=20)),
                ('id_object', models.PositiveBigIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_agent', to='contenttypes.contenttype')),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_ddia', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='NationalInformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_authority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('fax', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('rsfta', models.CharField(blank=True, max_length=100)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='aero_info_management.aerodrome')),
            ],
        ),
        migrations.CreateModel(
            name='RequestReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('agent_id', models.PositiveBigIntegerField()),
                ('id_object', models.PositiveBigIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reqs_referral_agent', to='contenttypes.contenttype')),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqs_referral_ddia', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='NationalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalinformer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.nationalinformer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalInformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aerodrome', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localinformer', to='aero_info_management.aerodrome')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aero_info_management.unit')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localinformer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.localinformer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSUPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(auto_now_add=True)),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('type_suppaip', models.CharField(choices=[('SUPP AIP N', 'SUPP AIP N'), ('SUPP AIP R', 'SUPP AIP R')], default='SUPP AIP N', max_length=15)),
                ('object', models.TextField()),
                ('code_ddia_replaced', models.CharField(blank=True, max_length=80, null=True)),
                ('aip_target_sections', models.TextField()),
                ('start_val_period', models.DateTimeField()),
                ('end_val_period', models.DateTimeField()),
                ('descriptive_text', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeNOTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(auto_now_add=True)),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('range_action', models.CharField(blank=True, max_length=120)),
                ('type_notam', models.CharField(choices=[('NOTAM N', 'NOTAM N'), ('NOTAM C', 'NOTAM C'), ('NOTAM R', 'NOTAM R')], default='NOTAM N', max_length=10)),
                ('coords', models.CharField(blank=True, max_length=120)),
                ('validity_period_type', models.CharField(choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], default='Prévue', max_length=15)),
                ('code_notam_replaceorcancel', models.CharField(blank=True, max_length=80, null=True)),
                ('start_val_period', models.DateTimeField()),
                ('end_val_period', models.DateTimeField()),
                ('daily_freq_start', models.TimeField()),
                ('daily_freq_end', models.TimeField()),
                ('daily_freq_type', models.CharField(choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], default='Prévue', max_length=30)),
                ('lower_vertical_limit', models.CharField(blank=True, max_length=50)),
                ('upper_vertical_limit', models.CharField(blank=True, max_length=50)),
                ('descriptive_text', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeAIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(auto_now_add=True)),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('subject', models.CharField(choices=[('Administratif', 'Administratif'), ('Administratif', 'Administratif')], max_length=50)),
                ('object', models.TextField()),
                ('descriptive_text', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DDIAModifHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.TextField()),
                ('prev_value', models.TextField()),
                ('field', models.CharField(max_length=50)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifshistory', to='aero_info_management.ddiahistory')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to='')),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerodrome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aero_info_management.aerodrome')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aero_info_management.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceStructureAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('prev_state', models.CharField(choices=[('en attente de vérification', 'en attente de vérification'), ('non admis', 'non admis')], max_length=40)),
                ('new_state', models.CharField(choices=[("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ('non conforme', 'non conforme'), ('non admis', 'non admis')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionsonddia', to='aero_info_management.agent')),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('ddia_type', 'object_id', 'prev_state')},
            },
        ),
        migrations.CreateModel(
            name='NationalInformerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('new_state', models.CharField(choices=[("en attente d'approbation", "en attente d'approbation"), ('non validé', 'non validé')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('national_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_inf_actions', to='aero_info_management.nationalagent')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('ddia_type', 'object_id', 'national_agent')},
            },
        ),
        migrations.CreateModel(
            name='LocalInformerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('prev_state', models.CharField(choices=[('en attente de vérification', 'en attente de vérification'), ('en attente de validation', 'en attente de validation')], max_length=40)),
                ('new_state', models.CharField(choices=[('en attente de publication', 'en attente de publication'), ('non approuvé', 'non approuvé')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ddia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('local_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_inf_actions', to='aero_info_management.localagent')),
                ('target_nationalinf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aero_info_management.nationalinformer')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('ddia_type', 'object_id', 'local_agent')},
            },
        ),
    ]
