# Generated by Django 3.2.5 on 2021-07-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrome',
            name='is_conceded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='subject',
            field=models.CharField(choices=[('Administratif', 'Administratif'), ('ATC', 'ATC'), ('Zone à statut particulier', 'Zone à statut particulier'), ('Carte', 'Carte'), ('Sécurité', 'Sécurité')], max_length=50),
        ),
    ]
