# Generated by Django 3.2.5 on 2021-07-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0003_auto_20210728_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandenotam',
            name='daily_freq_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='daily_freq_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
