# Generated by Django 3.2.5 on 2021-08-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0004_auto_20210728_0419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localinformeraction',
            unique_together={('ddia_type', 'object_id', 'prev_state')},
        ),
        migrations.AlterUniqueTogether(
            name='nationalinformeraction',
            unique_together={('ddia_type', 'object_id')},
        ),
    ]
