# Generated by Django 3.2.5 on 2021-08-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0005_auto_20210805_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinformer',
            name='aerodrome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localinformer', to='aero_info_management.aerodrome'),
        ),
    ]
