# Generated by Django 3.2.5 on 2021-08-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0006_alter_localinformer_aerodrome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeaic',
            options={'ordering': ['deposit_datetime']},
        ),
        migrations.AlterModelOptions(
            name='demandenotam',
            options={'ordering': ['deposit_datetime']},
        ),
        migrations.AlterModelOptions(
            name='demandesupp',
            options={'ordering': ['deposit_datetime']},
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('publié', 'publié'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('publié', 'publié'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('publié', 'publié'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.PositiveBigIntegerField()),
                ('event', models.CharField(max_length=20)),
                ('ddia_type', models.CharField(choices=[('NOTAM', 'NOTAM'), ('SUPP AIP', 'SUPP AIP'), ('AIC', 'AIC')], max_length=20)),
                ('ref_ddia', models.CharField(max_length=20)),
                ('new_ddia_state', models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission", "en attente d'admission"), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('publié', 'publié'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], max_length=50)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('receiver_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
