# Generated by Django 3.2.5 on 2021-08-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0007_auto_20210817_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_time']},
        ),
    ]
