# Generated by Django 3.2.5 on 2021-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0008_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinformeraction',
            name='new_state',
            field=models.CharField(choices=[("en attente d'admission", "en attente d'admission"), ("en attente d'approbation", "en attente d'approbation")], max_length=40),
        ),
        migrations.AlterField(
            model_name='nationalinformeraction',
            name='new_state',
            field=models.CharField(choices=[('en attente de publication', 'en attente de publication'), ('non approuvé', 'non approuvé'), ('en attente de publication', 'en attente de publication')], max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='nationalinformeraction',
            unique_together={('ddia_type', 'object_id', 'new_state')},
        ),
    ]
