# Generated by Django 3.2.5 on 2021-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0009_auto_20210825_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalinformer',
            name='email',
            field=models.EmailField(default='segc@ccaa.aero', max_length=254),
        ),
    ]
