# Generated by Django 3.2.5 on 2021-08-31 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aero_info_management', '0011_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='end_val_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='start_val_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='validity_period_type',
            field=models.CharField(blank=True, choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], default='Prévue', max_length=15, null=True),
        ),
    ]
