# Generated by Django 3.2.5 on 2021-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0012_auto_20210831_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
    ]
