# Generated by Django 3.2.5 on 2021-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0013_remove_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
