# Generated by Django 3.2.5 on 2021-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0014_notification_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandenotam',
            name='daily_freq_type',
            field=models.CharField(choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='validity_period_type',
            field=models.CharField(blank=True, choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], max_length=15, null=True),
        ),
    ]
