# Generated by Django 3.2.5 on 2021-09-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0015_auto_20210831_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinformer',
            name='aerodrome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localinformer', to='aero_info_management.aerodrome'),
        ),
    ]
