# Generated by Django 3.2.4 on 2021-07-01 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('location_ind', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome')),
            ],
        ),
        migrations.CreateModel(
            name='DDIAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'CREATION'), ('MODIFICATION', 'MODIFICATION'), ('CONTROLE', 'CONTROLE')], max_length=20)),
                ('id_object', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('type_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='LocalInformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NationalInformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('rsfta', models.CharField(max_length=100)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero_info_management.aerodrome')),
            ],
        ),
        migrations.CreateModel(
            name='RequestReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('id_demande', models.PositiveIntegerField()),
                ('type_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NationalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalinformer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.nationalinformer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localinformer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.localinformer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSUPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 20, 51, 49, 775327))),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('type_suppaip', models.CharField(choices=[('SUPP AIP N', 'SUPP AIP N'), ('SUPP AIP R', 'SUPP AIP R')], max_length=15)),
                ('object', models.TextField()),
                ('target_section', models.CharField(blank=True, max_length=80)),
                ('start_val_period', models.DateField()),
                ('end_val_period', models.DateField()),
                ('descriptive_text', models.TextField(blank=True)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.agent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeNOTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 20, 51, 49, 775327))),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('range_action', models.CharField(blank=True, max_length=80)),
                ('type_notam', models.CharField(choices=[('NOTAM N', 'NOTAM N'), ('NOTAM C', 'NOTAM C'), ('NOTAM R', 'NOTAM R')], max_length=10)),
                ('coords', models.CharField(blank=True, max_length=50)),
                ('periode_type_notam', models.CharField(max_length=15)),
                ('start_val_period', models.DateField()),
                ('end_val_period', models.DateField()),
                ('daily_freq_start', models.TimeField()),
                ('daily_freq_end', models.TimeField()),
                ('lower_limit', models.CharField(blank=True, max_length=50)),
                ('upper_limit', models.CharField(blank=True, max_length=50)),
                ('descriptive_text', models.TextField(blank=True)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.agent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeAIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_ddia', models.CharField(blank=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('brouillon', 'brouillon'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70)),
                ('deposit_datetime', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 20, 51, 49, 775327))),
                ('location_indicator', models.CharField(max_length=10)),
                ('publication_code', models.CharField(blank=True, max_length=70)),
                ('subject', models.TextField()),
                ('object', models.TextField()),
                ('descriptive_text', models.TextField(blank=True)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.agent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DDIAModifHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.TextField()),
                ('prev_value', models.TextField()),
                ('field', models.CharField(max_length=50)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero_info_management.ddiahistory')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddia_id', models.PositiveIntegerField()),
                ('pathname', models.FilePathField()),
                ('file', models.FileField(upload_to='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='local_informer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.localinformer'),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddia_id', models.PositiveIntegerField()),
                ('new_state', models.CharField(choices=[('en attente de publication', 'en attente de publication'), ('non approuvé', 'non approuvé')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('local_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='aero_info_management.localagent')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('content_type', 'ddia_id')},
            },
        ),
        migrations.CreateModel(
            name='Approbation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddia_id', models.PositiveIntegerField()),
                ('new_state', models.CharField(choices=[("en attente d'approbation", "en attente d'approbation"), ('non validé', 'non validé')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('national_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approbations', to='aero_info_management.nationalagent')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('content_type', 'ddia_id')},
            },
        ),
        migrations.CreateModel(
            name='ActionAgentOnDDIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddia_id', models.PositiveIntegerField()),
                ('prev_state', models.CharField(choices=[('en attente de vérification', 'en attente de vérification'), ('non admis', 'non admis')], max_length=40)),
                ('new_state', models.CharField(choices=[("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ('non conforme', 'non conforme'), ('non admis', 'non admis')], max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionsonddia', to='aero_info_management.agent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('content_type', 'ddia_id')},
            },
        ),
    ]
