# Generated by Django 3.2.4 on 2021-07-03 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeaic',
            options={'verbose_name': 'aic'},
        ),
        migrations.AlterModelOptions(
            name='demandenotam',
            options={'verbose_name': 'notam'},
        ),
        migrations.AlterModelOptions(
            name='demandesupp',
            options={'verbose_name': 'suppaip'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='source_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.unit'),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 36, 41, 893393)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 36, 41, 893393)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 36, 41, 893393)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rsfta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
