# Generated by Django 3.2.5 on 2021-07-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0002_auto_20210716_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerodrome',
            name='code',
        ),
    ]
