# Generated by Django 3.2.4 on 2021-07-06 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0002_auto_20210704_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='pathname',
        ),
        migrations.RemoveField(
            model_name='demandeaic',
            name='aerodrome',
        ),
        migrations.RemoveField(
            model_name='demandenotam',
            name='aerodrome',
        ),
        migrations.RemoveField(
            model_name='demandesupp',
            name='aerodrome',
        ),
        migrations.AlterField(
            model_name='agent',
            name='source_structure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aero_info_management.aerodrome'),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 55, 18, 539442)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 55, 18, 539442)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='periode_type_notam',
            field=models.CharField(choices=[('Estimée', 'Estimée'), ('Prévue', 'Prévue')], default='Prévue', max_length=15),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='type_notam',
            field=models.CharField(choices=[('NOTAM N', 'NOTAM N'), ('NOTAM C', 'NOTAM C'), ('NOTAM R', 'NOTAM R')], default='NOTAM N', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 55, 18, 539442)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='type_suppaip',
            field=models.CharField(choices=[('SUPP AIP N', 'SUPP AIP N'), ('SUPP AIP R', 'SUPP AIP R')], default='SUPP AIP N', max_length=15),
        ),
    ]
