# Generated by Django 3.2.4 on 2021-07-07 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0003_auto_20210707_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 15, 22, 34, 608285)),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 15, 22, 34, 608285)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 15, 22, 34, 608285)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='state',
            field=models.CharField(choices=[('brouillon', 'brouillon'), ('annulé', 'annulé'), ('en attente de vérification', 'en attente de vérification'), ("en attente d'admission   ", "en attente d'admission   "), ('en attente de validation', 'en attente de validation'), ("en attente d'approbation", "en attente d'approbation"), ('en attente de publication', 'en attente de publication'), ('non conforme', 'non conforme'), ('non admis', 'non admis'), ('non validé', 'non validé'), ('non approuvé', 'non approuvé')], default='brouillon', max_length=70),
        ),
    ]
