# Generated by Django 3.2.4 on 2021-07-07 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0004_auto_20210707_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 20, 2, 102331)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 20, 2, 102331)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 20, 2, 102331)),
        ),
        migrations.AlterUniqueTogether(
            name='actionagentonddia',
            unique_together={('content_type', 'ddia_id', 'prev_state')},
        ),
    ]
