# Generated by Django 3.2.4 on 2021-07-08 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0005_auto_20210707_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionagentonddia',
            old_name='ddia_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='approbation',
            old_name='ddia_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='ddia_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='ddia_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='ddiamodifhistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifshistory', to='aero_info_management.ddiahistory'),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 6, 44, 613462)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 6, 44, 613462)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 18, 6, 44, 613462)),
        ),
        migrations.AlterUniqueTogether(
            name='actionagentonddia',
            unique_together={('content_type', 'object_id', 'prev_state')},
        ),
        migrations.AlterUniqueTogether(
            name='approbation',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='validation',
            unique_together={('content_type', 'object_id')},
        ),
    ]
