# Generated by Django 3.2.4 on 2021-07-08 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0006_auto_20210708_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 25, 40, 14910)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 25, 40, 14910)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 25, 40, 14910)),
        ),
    ]
