# Generated by Django 3.2.4 on 2021-07-08 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aero_info_management', '0007_auto_20210708_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionagentonddia',
            old_name='content_type',
            new_name='ddia_type',
        ),
        migrations.RenameField(
            model_name='approbation',
            old_name='content_type',
            new_name='ddia_type',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='content_type',
            new_name='ddia_type',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='content_type',
            new_name='ddia_type',
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 27, 59, 932613)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 27, 59, 932613)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 27, 59, 932613)),
        ),
        migrations.AlterUniqueTogether(
            name='actionagentonddia',
            unique_together={('ddia_type', 'object_id', 'prev_state')},
        ),
        migrations.AlterUniqueTogether(
            name='approbation',
            unique_together={('ddia_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='validation',
            unique_together={('ddia_type', 'object_id')},
        ),
    ]
