# Generated by Django 3.2.4 on 2021-07-08 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_info_management', '0008_auto_20210708_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeaic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='demandenotam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='demandesupp',
            options={},
        ),
        migrations.RenameField(
            model_name='ddiahistory',
            old_name='type_object',
            new_name='ddia_type',
        ),
        migrations.AlterField(
            model_name='actionagentonddia',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='approbation',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ddiahistory',
            name='id_object',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='demandeaic',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 44, 7, 339698)),
        ),
        migrations.AlterField(
            model_name='demandenotam',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 44, 7, 339698)),
        ),
        migrations.AlterField(
            model_name='demandesupp',
            name='deposit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 44, 7, 339698)),
        ),
        migrations.AlterField(
            model_name='validation',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.DeleteModel(
            name='RequestReferral',
        ),
    ]
