MALE = "male"
FEMALE = "female"
SEX_CHOICES = (
    (MALE, MALE),
    (FEMALE, FEMALE),
)
SIGNUP_TOKEN = 'SIGNUP_TOKEN'
PASSWORD_TOKEN = 'PASSWORD_TOKEN'
EMAIL_TOKEN = 'EMAIL_TOKEN'
TOKEN_TYPES = (
    (SIGNUP_TOKEN, SIGNUP_TOKEN),
    (PASSWORD_TOKEN, PASSWORD_TOKEN),
    (EMAIL_TOKEN, EMAIL_TOKEN),
)
email_regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'

MINIMAL_PASSWORD_LENGTH = 8
SOURCE_AGENT = "Agent source"
SOURCE_VERIFIER = "Verificateur source"
SOURCE_STRUCTURE = "Structure source"
LOCAL_VERIFIER = "Verificateur local"
LOCAL_INFORMER = "Informateur local"
NATIONAL_INFORMER = "Informateur national"


USERS_ROLES = (
    (SOURCE_AGENT, SOURCE_AGENT),
    (SOURCE_VERIFIER, SOURCE_VERIFIER),
    (SOURCE_STRUCTURE, SOURCE_STRUCTURE),
    (LOCAL_VERIFIER, LOCAL_VERIFIER),
    (LOCAL_INFORMER, LOCAL_INFORMER),
    (NATIONAL_INFORMER, NATIONAL_INFORMER)
)
