SEX_CHOICES = (
    ("male", "male"),
    ("female", "female")
)

DRAFT_STATE = "brouillon" 
PENDING_ADMISSION_STATE = "en attente d'admission"
PENDING_VERIFICATION_STATE = "en attente de vérification"
PENDING_VALIDATION_STATE = "en attente de validation"
PENDING_APPROVAL_STATE = "en attente d'approbation"
PENDING_PUBLICATION_STATE = "en attente de publication"
PUBLISHED_STATE = "publié"
NON_CONFORMING_STATE = "non conforme"
NOT_ADMITTED_STATE = "non admis"
NOT_VALIDATED_STATE = "non validé"
NOT_APPROVED_STATE = "non approuvé"
CANCELLED_STATE = "annulé"

STATES = (
    (DRAFT_STATE, DRAFT_STATE),
    (CANCELLED_STATE, CANCELLED_STATE),
    (PENDING_VERIFICATION_STATE, PENDING_VERIFICATION_STATE),
    (PENDING_ADMISSION_STATE, PENDING_ADMISSION_STATE),
    (PENDING_VALIDATION_STATE, PENDING_VALIDATION_STATE),
    (PENDING_APPROVAL_STATE, PENDING_APPROVAL_STATE),
    (PENDING_PUBLICATION_STATE, PENDING_PUBLICATION_STATE),
    (PUBLISHED_STATE, PUBLISHED_STATE),
    (NON_CONFORMING_STATE, NON_CONFORMING_STATE),
    (NOT_ADMITTED_STATE, NOT_ADMITTED_STATE),
    (NOT_VALIDATED_STATE, NOT_VALIDATED_STATE),
    (NOT_APPROVED_STATE, NOT_APPROVED_STATE)
)
NOTAMN = "NOTAM N"
NOTAMC = "NOTAM C"
NOTAMR = "NOTAM R"
TYPES_NOTAM = (
    (NOTAMN, NOTAMN),
    (NOTAMC, NOTAMC),
    (NOTAMR, NOTAMR)
)
SUPPAIPN = "SUPP AIP N"
SUPPAIPR = "SUPP AIP R"
TYPES_SUPPAIP = (
    (SUPPAIPN, SUPPAIPN),
    (SUPPAIPR, SUPPAIPR)
)

ESTIMATED = "Estimée"
PLANNED = "Prévue"
PERIOD_TYPES = (
    (ESTIMATED, ESTIMATED),
    (PLANNED, PLANNED)
)

NOTAM = "NOTAM"
SUPPAIP = "SUPP AIP"
AIC = "AIC"
TYPES_DDIA = (
    (NOTAM, NOTAM),
    (SUPPAIP, SUPPAIP),
    (AIC, AIC)
)

SOURCE_AGENT = "Agent source"
SOURCE_VERIFIER = "Verificateur source"
SOURCE_STRUCTURE = "Structure source"
LOCAL_VERIFIER = "Verificateur local"
LOCAL_INFORMER = "Informateur local"
NATIONAL_INFORMER = "Informateur national"

USERS_ROLES = (
    (SOURCE_AGENT, SOURCE_AGENT),
    (SOURCE_VERIFIER, SOURCE_VERIFIER),
    (SOURCE_STRUCTURE, SOURCE_STRUCTURE),
    (LOCAL_VERIFIER, LOCAL_VERIFIER),
    (LOCAL_INFORMER, LOCAL_INFORMER),
    (NATIONAL_INFORMER, NATIONAL_INFORMER)
)




CREATE_ACTION = "CREATION"
MODIF_ACTION = "MODIFICATION"
CONTROLE_ACTION = "CONTROLE"
TYPES_ACTION = (
    (CREATE_ACTION, CREATE_ACTION),
    (MODIF_ACTION, MODIF_ACTION),
    (CONTROLE_ACTION, CONTROLE_ACTION),   
)

STATES_AFTER_VALIDATION = (
    (PENDING_APPROVAL_STATE, PENDING_APPROVAL_STATE),
    (NOT_VALIDATED_STATE, NOT_VALIDATED_STATE),
)

STATES_AFTER_APPROBATION = (
    (PENDING_PUBLICATION_STATE, PENDING_PUBLICATION_STATE),
    (NOT_APPROVED_STATE, NOT_APPROVED_STATE)
)

STATES_AFTER_NATIONALINF_ACTION = (
    (PENDING_PUBLICATION_STATE, PENDING_PUBLICATION_STATE),
    (NOT_APPROVED_STATE, NOT_APPROVED_STATE),
    (PENDING_PUBLICATION_STATE, PENDING_PUBLICATION_STATE),
)

PREVSTATES_FOR_AERODROME_AGENT = (
    (PENDING_VERIFICATION_STATE, PENDING_VERIFICATION_STATE),
    (NOT_ADMITTED_STATE, NOT_ADMITTED_STATE),
)

NEXTSTATES_FOR_AERODROME_AGENT = (
    (PENDING_ADMISSION_STATE, PENDING_ADMISSION_STATE),
    (PENDING_VALIDATION_STATE, PENDING_VALIDATION_STATE),
    (NON_CONFORMING_STATE, NON_CONFORMING_STATE),
    (NOT_ADMITTED_STATE, NOT_ADMITTED_STATE),
)

ACCEPT = 'accept'
REJECT = 'reject'

ADMINISTRATIVE_SUBJ = "Administratif"
ATC_SUBJ = "ATC"
SECURITY_SUBJ = "Sécurité"
ZONE_SUBJ = "Zone à statut particulier"
MAP_SUBJ = "Carte"
AIC_SUBJECTS = (
    (ADMINISTRATIVE_SUBJ, ADMINISTRATIVE_SUBJ),
    (ATC_SUBJ, ATC_SUBJ),
    (ZONE_SUBJ, ZONE_SUBJ),
    (MAP_SUBJ, MAP_SUBJ),
    (SECURITY_SUBJ, SECURITY_SUBJ),
)

PAGE_DDIA_LIST_SIZE = 5